FirstApp/Models/Catagory.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace FirstApp.Models
{
    public class Catagory
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [DisplayName("Display Order")]
        [Range(1,100,ErrorMessage ="Must be between 1 and 100...")]
        public int DisplayOrder { get; set; }
        public DateTime CreatedDateTime { get; set; } = DateTime.Now;

    }
}

FirstApp/Models/ErrorViewModel.cs
namespace FirstApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FirstApp/Controllers/CatagoryController.cs
using FirstApp.Models;
using FirstApp.mydatabase;
using Microsoft.AspNetCore.Mvc;

namespace FirstApp.Controllers
{
    public class CatagoryController : Controller
    {
        private readonly ApplicationDbContext _db;
        public CatagoryController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Catagory> objCatagoryList=_db.Catagories.ToList();
            return View(objCatagoryList);
        }
        //CreateGET
        public IActionResult Create()
        {
            
            return View();
        }

        //CreatePOST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Catagory obj)
        {
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("CustomError", "DisplayOrder and Name cannot be same");

            }
            if (ModelState.IsValid)
            {
                _db.Catagories.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Catagory created successfully";

                return RedirectToAction("Index");
            }
            else { return View(obj); }
        }

        //editGET
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var catagoryFromDb = _db.Catagories.Find(id);
            if (catagoryFromDb == null)
            {
                return NotFound();
            }

            return View(catagoryFromDb);
        }

        //editPOST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Catagory obj)
        {
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("CustomError", "DisplayOrder and Name cannot be same");

            }
            if (ModelState.IsValid)
            {
                _db.Catagories.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Catagory edited successfully";


                return RedirectToAction("Index");
            }
            else { return View(obj); }
        }

        //deleteGET
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var catagoryFromDb = _db.Catagories.Find(id);
            if (catagoryFromDb == null)
            {
                return NotFound();
            }

            return View(catagoryFromDb);
        }

        //editPOST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _db.Catagories.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
                _db.Catagories.Remove(obj);
                _db.SaveChanges();
            TempData["success"] = "Catagory deleted successfully";

            return RedirectToAction("Index");
           
        }


    }
}

FirstApp/Controllers/HomeController.cs
using FirstApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FirstApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FirstApp/Views/Catagory/Create.cshtml
@model Catagory;

<form method="post">

    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create Catagory</h2>
            <hr/>
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control">.
            <span asp-validation-for="Name" class="text-danger"></span>

        </div>
          <div class="mb-3">
            <label asp-for="DisplayOrder"></label>
            <input asp-for="DisplayOrder" class="form-control">
            <span asp-validation-for="DisplayOrder" class="text-danger"></span>


        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-controller="Catagory"asp-action='Index' class="btn btn-secondary" style="widht:150px">Back to List</a>
    </div>

</form> 
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

FirstApp/Views/Catagory/Delete.cshtml
@model Catagory;

<form method="post" asp-action="DeletePOST">

    <input asp-for="Id" hidden />

    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete Catagory</h2>
            <hr/>
        </div>
       @* <div asp-validation-summary="All"></div>*@
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" disabled>
            @*<span asp-validation-for="Name" class="text-danger"></span>*@

        </div>
          <div class="mb-3">
            <label asp-for="DisplayOrder"></label>
            <input asp-for="DisplayOrder" class="form-control" disabled>
            @*<span asp-validation-for="DisplayOrder" class="text-danger"></span>*@


        </div>
        <button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
        <a asp-controller="Catagory"asp-action='Index' class="btn btn-secondary" 
        style="widht:150px">Back to List</a>
    </div>

</form> 
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

FirstApp/Views/Catagory/Edit.cshtml
@model Catagory;

<form method="post"  >
    

    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Catagory</h2>
            <hr/>
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control">.
            <span asp-validation-for="Name" class="text-danger"></span>

        </div>
          <div class="mb-3">
            <label asp-for="DisplayOrder"></label>
            <input asp-for="DisplayOrder" class="form-control">
            <span asp-validation-for="DisplayOrder" class="text-danger"></span>


        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
        <a asp-controller="Catagory"asp-action='Index' class="btn btn-secondary" style="widht:150px">Back to List</a>
    </div>

</form> 
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

FirstApp/Views/Catagory/Index.cshtml
@model IEnumerable<Catagory>



@{
    ViewData["Title"] = "Index";
}



<div class='container p-3'>
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Catagory List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Catagory" asp-action="Create" class="btn btn-primary ">
                <i class="bi bi-plus-circle"></i>&nbsp; Create New Catagory</a>
        </div>
    </div>
    <br/><br/>
<table class="table table-bordered table-striped" style="width:100%">
<thead>
    <tr>
        <th>catagory</th>
        <th>display order</th>
        <th></th>
    </tr>
</thead>
<tbody>
    @foreach( var obj in Model)
        {
            <tr>
                <td width="50%">@obj.Name</td>
                <td width="30%">@obj.DisplayOrder</td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Catagory" asp-action="Edit" asp-route-id="@obj.Id" 
                        class="btn btn-primary mc-2"><i class="bi bi-pencil-square"></i>Edit</a>
                          <a asp-controller="Catagory" asp-action="Delete" asp-route-id="@obj.Id" 
                        class="btn btn-danger mc-2"><i class="bi bi-thrash-fill"></i>Delete</a>
                    </div>
                </td>
            </tr>

        }
    </tbody>
</table>
</div>

FirstApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building food Web apps with ASP.NET Core</a>.</p>
</div>

FirstApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FirstApp</title>
    <link rel="stylesheet" href="~/css/bootsWatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FirstApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.0/font/bootstrap-icons.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor02">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
         <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </li>
        <li class="nav-item">
        <a class="nav-link" asp-area="" asp-controller="Catagory" asp-action="Index">Catagory</a>

        </li>
        
        @*<li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Separated link</a>
          </div>
        </li>*@
      </ul>
      <form class="d-flex">
        <input class="form-control me-sm-2" type="text" placeholder="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
        @*<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FirstApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Catagory" asp-action="Index">Catagory</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>*@
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification"/>
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted bg-dark">
        <div class="container">
            &copy; 2022 - FirstApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FirstApp/Views/Shared/_Notification.cshtml
@if(TempData["Success"]!=null){
    <script src="~/lib/jquery/dist/jquery.min.js"> </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
toastr.success('@TempData["Success"]');  
    </script>
}

@if(TempData["Error"]!=null){
      <script src="~/lib/jquery/dist/jquery.min.js"> </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
    toastr.error('@TempData["Error"]'); 
    </script>
}